"""'3'

Revision ID: 327794e2b005
Revises: d2ec04599a39
Create Date: 2019-10-16 20:47:33.263454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327794e2b005'
down_revision = 'd2ec04599a39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
